Project/Controllers/ContactUsController.cs
using Project.Filters;
using Project.Models;
using Project.Models.Services;
using Project.ModelView;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Controllers
{
    public class ContactUsController : Controller
    {
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                ContactUsViewModel viewModel = new ContactUsViewModel();
                using (TouristContext db = new TouristContext())
                {
                    var account = db.Account.FirstOrDefault(a => a.Email == User.Identity.Name);
                    if (account != null)
                    {
                        viewModel.Email = account.Email;
                        viewModel.FirstName = account.FirstName;
                        viewModel.LastName = account.LastName;
                        viewModel.Country = account.Country;
                    }
                    return View(viewModel);
                }

            }
            return View();
        }

        [HttpPost]
        [ExceptionLogger]
        public ActionResult Index(ContactUsViewModel model)
        {
            if (ModelState.IsValid)
            {
                Mail.Send(model.Topic, model.FirstName, model.LastName, model.Email, model.Country, model.Text);
            }

            return View(model);
        }
    }
}

Project/Views/Shared/HeaderMenu.cshtml
@model string

<ul class="nav navbar-nav">
    <li class="@(Model == "Index" ? "active" : null)">@Html.ActionLink("Home", "Index", "Home")</li>
    <li class="@(Model == "About" ? "active" : null)">@Html.ActionLink("About", "About", "Home")</li>
    <li class="@(Model == "Contact" ? "active" : null)">@Html.ActionLink("Contact us", "Index", "ContactUs")</li>
</ul>

@if (User.Identity.IsAuthenticated)
{
    <ul class="nav navbar-nav navbar-right header-pr">
        <li class="pr-10 hidden-xs hidden-sm"><span class="email-style">@User.Identity.Name</span></li>
        <li class="@(Model == "Settings" ? "active" : null)"><a href="@Url.Action("Settings", "Account")"><span class="glyphicon glyphicon-cog"></span> Settings</a></li>
        <li class="@(Model == "SignUp" ? "active" : null)"><a href="@Url.Action("LogOut", "Account")"><span class="glyphicon glyphicon-user"></span> Log out</a></li>
    </ul>
}
else
{
    <ul class="nav navbar-nav navbar-right header-pr">
        <li class="@(Model == "SignUp" ? "active" : null)"><a href="@Url.Action("SignUp", "Account")"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li class="@(Model == "Login" ? "active" : null)"><a href="@Url.Action("Login", "Account")"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
}

Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse border-radius-none mb-0"> 
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Tourist", "Index", "Home", new { @class = "navbar-brand header-pl" })
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                @if (IsSectionDefined("HeaderMenu"))
                {
                    @RenderSection("HeaderMenu")
                }
                else
                {
                    @Html.Partial("HeaderMenu", "Index")
                }
            </div>
        </div>
    </div>
   
    @RenderSection("Content", required: false)
     
    <div class="container-fluid mt-20">
        <p class="text-center">&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </div>

    @* Script code *@
  
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB7ZMMLBCvl7qIv55Sk7PAWQCDxYLfzF0g"></script>

    <script>
        var $qwe = "qweqwe";
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>